### ISSUE TITLE
scroll scrolltop issue

### ISSUE THREAD

**Issue by ryuhangyeong** [ryuhangyeong/daily-health-originer#5]
# 문제
무한 스크롤을 구현하기 위해서, 사용자의 현재 스크롤 위치를 알 필요가 있다. 근데, scrolltop이 0으로 고정되는 현상 발생. 검색을 통해서 해결해보려고 했다.
```javascript
const { scrollTop } = document.body // 0
```
## 해본것 
최상위(html) height: 100%; overflow: hiddle;
스크롤하는 창 자체가 높이를 들고 있어야 한다는 글을 보아서, height값을 주었지만, 인식하지 못하였다.

```css
body {
   height: 100%;
   overflow: hiddle;
}
```

## 수 많은 삽질 끝에 알아낸 솔루션

```javascript
const { scrollTop } = document.documentElement
```
